/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ProtocolCheckerType = t.enumtype({
  "QueryDepthResult": "queryDepth",
});

export const IDepthResult = t.iface([], {
  "asks": t.array(t.tuple("string", "string", "string")),
  "bids": t.array(t.tuple("string", "string", "string")),
});

const exportedTypeSuite: t.ITypeSuite = {
  ProtocolCheckerType,
  IDepthResult,
};
export default exportedTypeSuite;
