/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const GoodTempalte = t.iface([], {
  "age": "number",
  "name": "string",
  "likes": t.array("string"),
});

export const GoodTempalte2 = t.iface([], {
  "age": "number",
  "name": "string",
  "dislikes": t.array("string"),
});

const exportedTypeSuite: t.ITypeSuite = {
  GoodTempalte,
  GoodTempalte2,
};
export default exportedTypeSuite;
